# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c4ccbaca46962c6975cf3d1500ac8cfd"
name = "risk-mate"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = ["orders/create"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["orders/updated"]
  uri = "/webhooks"

  [[webhooks.subscriptions]]
  topics = ["app/uninstalled"]
  uri = "/webhooks"

